import Head from 'next/head'
import Image from 'next/image'
import { Container } from 'react-bootstrap'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div className='bg-light'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Container>
          <h1>hwoierh</h1>
        </Container>
      </main>

      <footer>
      </footer>
    </div>
  )
}
